-- ============================================================
-- FENSTERMEISTER - UPDATE DEFAULT PRODUCTS & WINDOWS IN SUPABASE
-- Run this script in your Supabase SQL Editor:
-- Dashboard -> SQL Editor -> New Query -> Paste & Run
-- ============================================================

DO $$
BEGIN

    -- Delete old non-window products if any exist
    DELETE FROM public.products WHERE id NOT LIKE 'prod-win-%' AND id NOT IN ('prod-001', 'prod-002');

    INSERT INTO public.products (
        id, name, sku, description, image, purchase_price, selling_price, wholesale_price,
        vat_rate, discount, unit, stock, min_stock_alert, category, type, status, notes, svg_key, custom_specs
    ) VALUES (
        'prod-001',
        'Window Installation & Fitting',
        'SRV-WIN-INSTALL',
        'Complete professional installation, weatherproofing, thermal sealing, perimeter foaming and alignment of house windows.',
        'https://images.unsplash.com/photo-1503708998063-fb28b6dce510?auto=format&fit=crop&w=400&q=80',
        150,
        450,
        0,
        19,
        0,
        'service',
        999,
        5,
        'Services',
        'service',
        'active',
        'Billed per window unit installed.',
        NULL,
        '{}'::jsonb
    )
    ON CONFLICT (id) DO UPDATE SET
        name = EXCLUDED.name,
        sku = EXCLUDED.sku,
        description = EXCLUDED.description,
        image = EXCLUDED.image,
        purchase_price = EXCLUDED.purchase_price,
        selling_price = EXCLUDED.selling_price,
        wholesale_price = EXCLUDED.wholesale_price,
        vat_rate = EXCLUDED.vat_rate,
        discount = EXCLUDED.discount,
        unit = EXCLUDED.unit,
        stock = EXCLUDED.stock,
        min_stock_alert = EXCLUDED.min_stock_alert,
        category = EXCLUDED.category,
        type = EXCLUDED.type,
        status = EXCLUDED.status,
        notes = EXCLUDED.notes,
        svg_key = EXCLUDED.svg_key,
        custom_specs = EXCLUDED.custom_specs;

    INSERT INTO public.products (
        id, name, sku, description, image, purchase_price, selling_price, wholesale_price,
        vat_rate, discount, unit, stock, min_stock_alert, category, type, status, notes, svg_key, custom_specs
    ) VALUES (
        'prod-002',
        'Triple Glazing Upgrade',
        'OPT-GLZ-TRIPLE',
        'Argon-filled low-E triple pane glass unit for high acoustic and thermal insulation.',
        'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=400&q=80',
        85,
        220,
        0,
        19,
        0,
        'sqm',
        500,
        5,
        'Upgrades',
        'product',
        'active',
        NULL,
        NULL,
        '{}'::jsonb
    )
    ON CONFLICT (id) DO UPDATE SET
        name = EXCLUDED.name,
        sku = EXCLUDED.sku,
        description = EXCLUDED.description,
        image = EXCLUDED.image,
        purchase_price = EXCLUDED.purchase_price,
        selling_price = EXCLUDED.selling_price,
        wholesale_price = EXCLUDED.wholesale_price,
        vat_rate = EXCLUDED.vat_rate,
        discount = EXCLUDED.discount,
        unit = EXCLUDED.unit,
        stock = EXCLUDED.stock,
        min_stock_alert = EXCLUDED.min_stock_alert,
        category = EXCLUDED.category,
        type = EXCLUDED.type,
        status = EXCLUDED.status,
        notes = EXCLUDED.notes,
        svg_key = EXCLUDED.svg_key,
        custom_specs = EXCLUDED.custom_specs;

    INSERT INTO public.products (
        id, name, sku, description, image, purchase_price, selling_price, wholesale_price,
        vat_rate, discount, unit, stock, min_stock_alert, category, type, status, notes, svg_key, custom_specs
    ) VALUES (
        'prod-win-casement',
        'Casement Window',
        'WIN-CASEMENT',
        'Hinged at the side and opening outward to the left or right like a door. Delivers maximum top-to-bottom ventilation and creates the tightest compression weather seal among operable windows. Includes uPVC / Vinyl frame, Double Pane Low-E Argon, multi-point locking hardware, and standard 18" – 36" sizing.',
        NULL,
        231,
        420,
        344,
        20,
        0,
        'unit',
        25,
        5,
        'Windows & Glazing',
        'product',
        'active',
        'U-Factor: 0.22 – 0.27 | SHGC: 0.24 – 0.30 | Energy Star: Most Efficient',
        'casement',
        '{"U-Factor":"0.22 – 0.27","SHGC":"0.24 – 0.30","Sound STC":"32 – 36 dB","Standard Dimensions":"18\" – 36\"","Energy Rating":"Most Efficient","Opening Mechanism":"Side-hinged sash swings outward via hand crank or push bar"}'::jsonb
    )
    ON CONFLICT (id) DO UPDATE SET
        name = EXCLUDED.name,
        sku = EXCLUDED.sku,
        description = EXCLUDED.description,
        image = EXCLUDED.image,
        purchase_price = EXCLUDED.purchase_price,
        selling_price = EXCLUDED.selling_price,
        wholesale_price = EXCLUDED.wholesale_price,
        vat_rate = EXCLUDED.vat_rate,
        discount = EXCLUDED.discount,
        unit = EXCLUDED.unit,
        stock = EXCLUDED.stock,
        min_stock_alert = EXCLUDED.min_stock_alert,
        category = EXCLUDED.category,
        type = EXCLUDED.type,
        status = EXCLUDED.status,
        notes = EXCLUDED.notes,
        svg_key = EXCLUDED.svg_key,
        custom_specs = EXCLUDED.custom_specs;

    INSERT INTO public.products (
        id, name, sku, description, image, purchase_price, selling_price, wholesale_price,
        vat_rate, discount, unit, stock, min_stock_alert, category, type, status, notes, svg_key, custom_specs
    ) VALUES (
        'prod-win-double_hung',
        'Double-Hung Window',
        'WIN-DOUBLE-HUNG',
        'The timeless American classic. Featuring two vertically sliding sashes, allowing cool fresh air to enter through the bottom while warm indoor air escapes through the lowered top sash. Includes uPVC / Vinyl frame, Double Pane Low-E Argon, multi-point locking hardware, and standard 24" – 48" sizing.',
        NULL,
        209,
        380,
        312,
        20,
        0,
        'unit',
        25,
        5,
        'Windows & Glazing',
        'product',
        'active',
        'U-Factor: 0.25 – 0.30 | SHGC: 0.26 – 0.32 | Energy Star: Certified',
        'double_hung',
        '{"U-Factor":"0.25 – 0.30","SHGC":"0.26 – 0.32","Sound STC":"29 – 34 dB","Standard Dimensions":"24\" – 48\"","Energy Rating":"Certified","Opening Mechanism":"Both upper and lower sashes slide vertically in tracks"}'::jsonb
    )
    ON CONFLICT (id) DO UPDATE SET
        name = EXCLUDED.name,
        sku = EXCLUDED.sku,
        description = EXCLUDED.description,
        image = EXCLUDED.image,
        purchase_price = EXCLUDED.purchase_price,
        selling_price = EXCLUDED.selling_price,
        wholesale_price = EXCLUDED.wholesale_price,
        vat_rate = EXCLUDED.vat_rate,
        discount = EXCLUDED.discount,
        unit = EXCLUDED.unit,
        stock = EXCLUDED.stock,
        min_stock_alert = EXCLUDED.min_stock_alert,
        category = EXCLUDED.category,
        type = EXCLUDED.type,
        status = EXCLUDED.status,
        notes = EXCLUDED.notes,
        svg_key = EXCLUDED.svg_key,
        custom_specs = EXCLUDED.custom_specs;

    INSERT INTO public.products (
        id, name, sku, description, image, purchase_price, selling_price, wholesale_price,
        vat_rate, discount, unit, stock, min_stock_alert, category, type, status, notes, svg_key, custom_specs
    ) VALUES (
        'prod-win-single_hung',
        'Single-Hung Window',
        'WIN-SINGLE-HUNG',
        'Cost-effective alternative to double-hung windows. The upper sash is permanently sealed into the master frame, eliminating air infiltration from the upper joints. Includes uPVC / Vinyl frame, Double Pane Low-E, multi-point locking hardware, and standard 20" – 44" sizing.',
        NULL,
        160,
        290,
        238,
        20,
        0,
        'unit',
        25,
        5,
        'Windows & Glazing',
        'product',
        'active',
        'U-Factor: 0.24 – 0.29 | SHGC: 0.25 – 0.30 | Energy Star: Certified',
        'single_hung',
        '{"U-Factor":"0.24 – 0.29","SHGC":"0.25 – 0.30","Sound STC":"30 – 34 dB","Standard Dimensions":"20\" – 44\"","Energy Rating":"Certified","Opening Mechanism":"Bottom sash slides vertically while top sash remains stationary"}'::jsonb
    )
    ON CONFLICT (id) DO UPDATE SET
        name = EXCLUDED.name,
        sku = EXCLUDED.sku,
        description = EXCLUDED.description,
        image = EXCLUDED.image,
        purchase_price = EXCLUDED.purchase_price,
        selling_price = EXCLUDED.selling_price,
        wholesale_price = EXCLUDED.wholesale_price,
        vat_rate = EXCLUDED.vat_rate,
        discount = EXCLUDED.discount,
        unit = EXCLUDED.unit,
        stock = EXCLUDED.stock,
        min_stock_alert = EXCLUDED.min_stock_alert,
        category = EXCLUDED.category,
        type = EXCLUDED.type,
        status = EXCLUDED.status,
        notes = EXCLUDED.notes,
        svg_key = EXCLUDED.svg_key,
        custom_specs = EXCLUDED.custom_specs;

    INSERT INTO public.products (
        id, name, sku, description, image, purchase_price, selling_price, wholesale_price,
        vat_rate, discount, unit, stock, min_stock_alert, category, type, status, notes, svg_key, custom_specs
    ) VALUES (
        'prod-win-sliding',
        'Sliding Window',
        'WIN-SLIDING',
        'Horizontal sliding window units offering expansive glass widths and effortless lateral glide. Exceptional for rooms where wall width exceeds vertical height. Includes uPVC / Vinyl frame, Double Pane Low-E, multi-point locking hardware, and standard 36" – 84" sizing.',
        NULL,
        198,
        360,
        295,
        20,
        0,
        'unit',
        25,
        5,
        'Windows & Glazing',
        'product',
        'active',
        'U-Factor: 0.26 – 0.31 | SHGC: 0.25 – 0.32 | Energy Star: Certified',
        'sliding',
        '{"U-Factor":"0.26 – 0.31","SHGC":"0.25 – 0.32","Sound STC":"30 – 33 dB","Standard Dimensions":"36\" – 84\"","Energy Rating":"Certified","Opening Mechanism":"Sashes slide horizontally along smooth brass or nylon roller tracks"}'::jsonb
    )
    ON CONFLICT (id) DO UPDATE SET
        name = EXCLUDED.name,
        sku = EXCLUDED.sku,
        description = EXCLUDED.description,
        image = EXCLUDED.image,
        purchase_price = EXCLUDED.purchase_price,
        selling_price = EXCLUDED.selling_price,
        wholesale_price = EXCLUDED.wholesale_price,
        vat_rate = EXCLUDED.vat_rate,
        discount = EXCLUDED.discount,
        unit = EXCLUDED.unit,
        stock = EXCLUDED.stock,
        min_stock_alert = EXCLUDED.min_stock_alert,
        category = EXCLUDED.category,
        type = EXCLUDED.type,
        status = EXCLUDED.status,
        notes = EXCLUDED.notes,
        svg_key = EXCLUDED.svg_key,
        custom_specs = EXCLUDED.custom_specs;

    INSERT INTO public.products (
        id, name, sku, description, image, purchase_price, selling_price, wholesale_price,
        vat_rate, discount, unit, stock, min_stock_alert, category, type, status, notes, svg_key, custom_specs
    ) VALUES (
        'prod-win-bay',
        'Bay Window',
        'WIN-BAY',
        'A striking architectural focal point extending outward from the exterior wall. Creates interior depth, expansive 180° perimeter views, and can be outfitted with an integrated window seat or display ledge. Includes Wood-Clad frame, High-Performance Low-E Argon, multi-point locking hardware, and standard 48" – 120" sizing.',
        NULL,
        798,
        1450,
        1189,
        20,
        0,
        'unit',
        25,
        5,
        'Windows & Glazing',
        'product',
        'active',
        'U-Factor: 0.24 – 0.28 | SHGC: 0.27 – 0.33 | Energy Star: Most Efficient',
        'bay',
        '{"U-Factor":"0.24 – 0.28","SHGC":"0.27 – 0.33","Sound STC":"34 – 38 dB","Standard Dimensions":"48\" – 120\"","Energy Rating":"Most Efficient","Opening Mechanism":"Central fixed picture window flanked by two 30° or 45° operable casements"}'::jsonb
    )
    ON CONFLICT (id) DO UPDATE SET
        name = EXCLUDED.name,
        sku = EXCLUDED.sku,
        description = EXCLUDED.description,
        image = EXCLUDED.image,
        purchase_price = EXCLUDED.purchase_price,
        selling_price = EXCLUDED.selling_price,
        wholesale_price = EXCLUDED.wholesale_price,
        vat_rate = EXCLUDED.vat_rate,
        discount = EXCLUDED.discount,
        unit = EXCLUDED.unit,
        stock = EXCLUDED.stock,
        min_stock_alert = EXCLUDED.min_stock_alert,
        category = EXCLUDED.category,
        type = EXCLUDED.type,
        status = EXCLUDED.status,
        notes = EXCLUDED.notes,
        svg_key = EXCLUDED.svg_key,
        custom_specs = EXCLUDED.custom_specs;

    INSERT INTO public.products (
        id, name, sku, description, image, purchase_price, selling_price, wholesale_price,
        vat_rate, discount, unit, stock, min_stock_alert, category, type, status, notes, svg_key, custom_specs
    ) VALUES (
        'prod-win-bow',
        'Bow Window',
        'WIN-BOW',
        'A graceful, rounded architectural projection. Formed with four or more sashes joined at shallow angles (usually 10°–15°) creating a smooth continuous circular curve with panoramic exterior vistas. Includes Engineered Timber frame, Triple Pane Acoustic Low-E, multi-point locking hardware, and standard 60" – 144" sizing.',
        NULL,
        1018,
        1850,
        1517,
        20,
        0,
        'unit',
        25,
        5,
        'Windows & Glazing',
        'product',
        'active',
        'U-Factor: 0.24 – 0.29 | SHGC: 0.28 – 0.34 | Energy Star: Most Efficient',
        'bow',
        '{"U-Factor":"0.24 – 0.29","SHGC":"0.28 – 0.34","Sound STC":"35 – 39 dB","Standard Dimensions":"60\" – 144\"","Energy Rating":"Most Efficient","Opening Mechanism":"Curved assembly of 4, 5, or 6 equal-width sashes in gentle arc"}'::jsonb
    )
    ON CONFLICT (id) DO UPDATE SET
        name = EXCLUDED.name,
        sku = EXCLUDED.sku,
        description = EXCLUDED.description,
        image = EXCLUDED.image,
        purchase_price = EXCLUDED.purchase_price,
        selling_price = EXCLUDED.selling_price,
        wholesale_price = EXCLUDED.wholesale_price,
        vat_rate = EXCLUDED.vat_rate,
        discount = EXCLUDED.discount,
        unit = EXCLUDED.unit,
        stock = EXCLUDED.stock,
        min_stock_alert = EXCLUDED.min_stock_alert,
        category = EXCLUDED.category,
        type = EXCLUDED.type,
        status = EXCLUDED.status,
        notes = EXCLUDED.notes,
        svg_key = EXCLUDED.svg_key,
        custom_specs = EXCLUDED.custom_specs;

    INSERT INTO public.products (
        id, name, sku, description, image, purchase_price, selling_price, wholesale_price,
        vat_rate, discount, unit, stock, min_stock_alert, category, type, status, notes, svg_key, custom_specs
    ) VALUES (
        'prod-win-awning',
        'Awning Window',
        'WIN-AWNING',
        'Hinged at the top of the frame, the sash swings outward from the bottom like an awning umbrella. Enables 100% weather-protected ventilation even during heavy rain showers. Includes uPVC / Vinyl frame, Double Glazed Low-E Argon, multi-point locking hardware, and standard 20" – 48" sizing.',
        NULL,
        215,
        390,
        320,
        20,
        0,
        'unit',
        25,
        5,
        'Windows & Glazing',
        'product',
        'active',
        'U-Factor: 0.22 – 0.26 | SHGC: 0.23 – 0.29 | Energy Star: Most Efficient',
        'awning',
        '{"U-Factor":"0.22 – 0.26","SHGC":"0.23 – 0.29","Sound STC":"33 – 37 dB","Standard Dimensions":"20\" – 48\"","Energy Rating":"Most Efficient","Opening Mechanism":"Top-hinged sash swings outward from the bottom via scissors crank"}'::jsonb
    )
    ON CONFLICT (id) DO UPDATE SET
        name = EXCLUDED.name,
        sku = EXCLUDED.sku,
        description = EXCLUDED.description,
        image = EXCLUDED.image,
        purchase_price = EXCLUDED.purchase_price,
        selling_price = EXCLUDED.selling_price,
        wholesale_price = EXCLUDED.wholesale_price,
        vat_rate = EXCLUDED.vat_rate,
        discount = EXCLUDED.discount,
        unit = EXCLUDED.unit,
        stock = EXCLUDED.stock,
        min_stock_alert = EXCLUDED.min_stock_alert,
        category = EXCLUDED.category,
        type = EXCLUDED.type,
        status = EXCLUDED.status,
        notes = EXCLUDED.notes,
        svg_key = EXCLUDED.svg_key,
        custom_specs = EXCLUDED.custom_specs;

    INSERT INTO public.products (
        id, name, sku, description, image, purchase_price, selling_price, wholesale_price,
        vat_rate, discount, unit, stock, min_stock_alert, category, type, status, notes, svg_key, custom_specs
    ) VALUES (
        'prod-win-hopper',
        'Hopper Window',
        'WIN-HOPPER',
        'Hinged at the bottom, opening inward from the top. Originally engineered for basements and masonry foundation walls to prevent ground debris, mud, and water from entering. Includes uPVC / Vinyl frame, Double Pane Tempered Glass, multi-point locking hardware, and standard 20" – 42" sizing.',
        NULL,
        151,
        275,
        226,
        20,
        0,
        'unit',
        25,
        5,
        'Windows & Glazing',
        'product',
        'active',
        'U-Factor: 0.23 – 0.28 | SHGC: 0.24 – 0.30 | Energy Star: Certified',
        'hopper',
        '{"U-Factor":"0.23 – 0.28","SHGC":"0.24 – 0.30","Sound STC":"32 – 35 dB","Standard Dimensions":"20\" – 42\"","Energy Rating":"Certified","Opening Mechanism":"Bottom-hinged sash tilts inward from the top into the room"}'::jsonb
    )
    ON CONFLICT (id) DO UPDATE SET
        name = EXCLUDED.name,
        sku = EXCLUDED.sku,
        description = EXCLUDED.description,
        image = EXCLUDED.image,
        purchase_price = EXCLUDED.purchase_price,
        selling_price = EXCLUDED.selling_price,
        wholesale_price = EXCLUDED.wholesale_price,
        vat_rate = EXCLUDED.vat_rate,
        discount = EXCLUDED.discount,
        unit = EXCLUDED.unit,
        stock = EXCLUDED.stock,
        min_stock_alert = EXCLUDED.min_stock_alert,
        category = EXCLUDED.category,
        type = EXCLUDED.type,
        status = EXCLUDED.status,
        notes = EXCLUDED.notes,
        svg_key = EXCLUDED.svg_key,
        custom_specs = EXCLUDED.custom_specs;

    INSERT INTO public.products (
        id, name, sku, description, image, purchase_price, selling_price, wholesale_price,
        vat_rate, discount, unit, stock, min_stock_alert, category, type, status, notes, svg_key, custom_specs
    ) VALUES (
        'prod-win-picture',
        'Picture Window',
        'WIN-PICTURE',
        'Large, stationary monolithic glass pane with zero operating sashes or mechanical hardware. Engineered to frame scenic outdoor vistas like a live painting and flood interiors with boundless daylight. Includes Thermal Break Aluminum frame, Triple Pane Low-E Argon, multi-point locking hardware, and standard 24" – 120" sizing.',
        NULL,
        253,
        460,
        377,
        20,
        0,
        'unit',
        25,
        5,
        'Windows & Glazing',
        'product',
        'active',
        'U-Factor: 0.18 – 0.24 | SHGC: 0.22 – 0.32 | Energy Star: Most Efficient',
        'picture',
        '{"U-Factor":"0.18 – 0.24","SHGC":"0.22 – 0.32","Sound STC":"35 – 42 dB","Standard Dimensions":"24\" – 120\"","Energy Rating":"Most Efficient","Opening Mechanism":"Non-operable stationary direct-set glass in insulated frame"}'::jsonb
    )
    ON CONFLICT (id) DO UPDATE SET
        name = EXCLUDED.name,
        sku = EXCLUDED.sku,
        description = EXCLUDED.description,
        image = EXCLUDED.image,
        purchase_price = EXCLUDED.purchase_price,
        selling_price = EXCLUDED.selling_price,
        wholesale_price = EXCLUDED.wholesale_price,
        vat_rate = EXCLUDED.vat_rate,
        discount = EXCLUDED.discount,
        unit = EXCLUDED.unit,
        stock = EXCLUDED.stock,
        min_stock_alert = EXCLUDED.min_stock_alert,
        category = EXCLUDED.category,
        type = EXCLUDED.type,
        status = EXCLUDED.status,
        notes = EXCLUDED.notes,
        svg_key = EXCLUDED.svg_key,
        custom_specs = EXCLUDED.custom_specs;

    INSERT INTO public.products (
        id, name, sku, description, image, purchase_price, selling_price, wholesale_price,
        vat_rate, discount, unit, stock, min_stock_alert, category, type, status, notes, svg_key, custom_specs
    ) VALUES (
        'prod-win-arched',
        'Arch Top Window',
        'WIN-ARCHED',
        'Featuring a curved semicircular or radius arch top. Inspired by classic Roman and Renaissance Palladian architecture, radius windows bestow unmatched grandeur and historic charm to building elevations. Includes Curved Solid Wood frame, Insulated Double Low-E, multi-point locking hardware, and standard 24" – 72" sizing.',
        NULL,
        374,
        680,
        558,
        20,
        0,
        'unit',
        25,
        5,
        'Windows & Glazing',
        'product',
        'active',
        'U-Factor: 0.24 – 0.28 | SHGC: 0.25 – 0.31 | Energy Star: Certified',
        'arched',
        '{"U-Factor":"0.24 – 0.28","SHGC":"0.25 – 0.31","Sound STC":"33 – 37 dB","Standard Dimensions":"24\" – 72\"","Energy Rating":"Certified","Opening Mechanism":"Fixed decorative radius arch header over central or multi-lite sash"}'::jsonb
    )
    ON CONFLICT (id) DO UPDATE SET
        name = EXCLUDED.name,
        sku = EXCLUDED.sku,
        description = EXCLUDED.description,
        image = EXCLUDED.image,
        purchase_price = EXCLUDED.purchase_price,
        selling_price = EXCLUDED.selling_price,
        wholesale_price = EXCLUDED.wholesale_price,
        vat_rate = EXCLUDED.vat_rate,
        discount = EXCLUDED.discount,
        unit = EXCLUDED.unit,
        stock = EXCLUDED.stock,
        min_stock_alert = EXCLUDED.min_stock_alert,
        category = EXCLUDED.category,
        type = EXCLUDED.type,
        status = EXCLUDED.status,
        notes = EXCLUDED.notes,
        svg_key = EXCLUDED.svg_key,
        custom_specs = EXCLUDED.custom_specs;

    INSERT INTO public.products (
        id, name, sku, description, image, purchase_price, selling_price, wholesale_price,
        vat_rate, discount, unit, stock, min_stock_alert, category, type, status, notes, svg_key, custom_specs
    ) VALUES (
        'prod-win-tilt_and_turn',
        'Tilt & Turn Window',
        'WIN-TILT-AND-TURN',
        'The pinnacle of German and European engineering. A single heavy-duty handle controls both top micro-ventilation and full inward-swinging side access for effortless cleaning and emergency egress. Includes Multi-Chamber Steel-Reinforced uPVC frame, Triple Glazed Argon with Warm-Edge Spacers, multi-point locking hardware, and standard 24" – 54" sizing.',
        NULL,
        396,
        720,
        590,
        20,
        0,
        'unit',
        25,
        5,
        'Windows & Glazing',
        'product',
        'active',
        'U-Factor: 0.15 – 0.22 | SHGC: 0.20 – 0.28 | Energy Star: Most Efficient',
        'tilt_and_turn',
        '{"U-Factor":"0.15 – 0.22","SHGC":"0.20 – 0.28","Sound STC":"36 – 44 dB","Standard Dimensions":"24\" – 54\"","Energy Rating":"Most Efficient","Opening Mechanism":"Dual-action: Turn handle 90° to tilt inward at top; turn 180° to swing wide like a door"}'::jsonb
    )
    ON CONFLICT (id) DO UPDATE SET
        name = EXCLUDED.name,
        sku = EXCLUDED.sku,
        description = EXCLUDED.description,
        image = EXCLUDED.image,
        purchase_price = EXCLUDED.purchase_price,
        selling_price = EXCLUDED.selling_price,
        wholesale_price = EXCLUDED.wholesale_price,
        vat_rate = EXCLUDED.vat_rate,
        discount = EXCLUDED.discount,
        unit = EXCLUDED.unit,
        stock = EXCLUDED.stock,
        min_stock_alert = EXCLUDED.min_stock_alert,
        category = EXCLUDED.category,
        type = EXCLUDED.type,
        status = EXCLUDED.status,
        notes = EXCLUDED.notes,
        svg_key = EXCLUDED.svg_key,
        custom_specs = EXCLUDED.custom_specs;

    INSERT INTO public.products (
        id, name, sku, description, image, purchase_price, selling_price, wholesale_price,
        vat_rate, discount, unit, stock, min_stock_alert, category, type, status, notes, svg_key, custom_specs
    ) VALUES (
        'prod-win-skylight',
        'Roof Skylight',
        'WIN-SKYLIGHT',
        'Installed directly into the roof slope to bring down to 3x more daylight than vertical wall windows. Available in venting models with rain sensors that close automatically upon detecting precipitation. Includes Polyurethane Coated Timber frame, Impact Laminated Safety Glass with Neat Glass Self-Cleaning Coating, multi-point locking hardware, and standard 21" – 44" sizing.',
        NULL,
        468,
        850,
        697,
        20,
        0,
        'unit',
        25,
        5,
        'Windows & Glazing',
        'product',
        'active',
        'U-Factor: 0.22 – 0.26 | SHGC: 0.19 – 0.25 | Energy Star: Most Efficient',
        'skylight',
        '{"U-Factor":"0.22 – 0.26","SHGC":"0.19 – 0.25","Sound STC":"35 – 40 dB","Standard Dimensions":"21\" – 44\"","Energy Rating":"Most Efficient","Opening Mechanism":"Center-pivot or top-hung manual / solar-powered motorized roof vent"}'::jsonb
    )
    ON CONFLICT (id) DO UPDATE SET
        name = EXCLUDED.name,
        sku = EXCLUDED.sku,
        description = EXCLUDED.description,
        image = EXCLUDED.image,
        purchase_price = EXCLUDED.purchase_price,
        selling_price = EXCLUDED.selling_price,
        wholesale_price = EXCLUDED.wholesale_price,
        vat_rate = EXCLUDED.vat_rate,
        discount = EXCLUDED.discount,
        unit = EXCLUDED.unit,
        stock = EXCLUDED.stock,
        min_stock_alert = EXCLUDED.min_stock_alert,
        category = EXCLUDED.category,
        type = EXCLUDED.type,
        status = EXCLUDED.status,
        notes = EXCLUDED.notes,
        svg_key = EXCLUDED.svg_key,
        custom_specs = EXCLUDED.custom_specs;

    INSERT INTO public.products (
        id, name, sku, description, image, purchase_price, selling_price, wholesale_price,
        vat_rate, discount, unit, stock, min_stock_alert, category, type, status, notes, svg_key, custom_specs
    ) VALUES (
        'prod-win-jalousie',
        'Louvered Window',
        'WIN-JALOUSIE',
        'Composed of parallel horizontal glass slats set in metal clips. When cranked open, the slats tilt outward in unison like venetian blinds, providing 100% natural airflow in tropical and mild coastal climates. Includes Extruded Aluminum Frames with Heavy Duty Stainless Rivets frame, 6mm Heavy Tempered Clear or Tinted Glass Slats, multi-point locking hardware, and standard 24" – 48" sizing.',
        NULL,
        171,
        310,
        254,
        20,
        0,
        'unit',
        25,
        5,
        'Windows & Glazing',
        'product',
        'active',
        'U-Factor: 0.65 – 0.90 | SHGC: 0.45 – 0.60 | Energy Star: Standard',
        'jalousie',
        '{"U-Factor":"0.65 – 0.90","SHGC":"0.45 – 0.60","Sound STC":"22 – 26 dB","Standard Dimensions":"24\" – 48\"","Energy Rating":"Standard","Opening Mechanism":"Cranked mechanism tilts multiple horizontal glass slats simultaneously"}'::jsonb
    )
    ON CONFLICT (id) DO UPDATE SET
        name = EXCLUDED.name,
        sku = EXCLUDED.sku,
        description = EXCLUDED.description,
        image = EXCLUDED.image,
        purchase_price = EXCLUDED.purchase_price,
        selling_price = EXCLUDED.selling_price,
        wholesale_price = EXCLUDED.wholesale_price,
        vat_rate = EXCLUDED.vat_rate,
        discount = EXCLUDED.discount,
        unit = EXCLUDED.unit,
        stock = EXCLUDED.stock,
        min_stock_alert = EXCLUDED.min_stock_alert,
        category = EXCLUDED.category,
        type = EXCLUDED.type,
        status = EXCLUDED.status,
        notes = EXCLUDED.notes,
        svg_key = EXCLUDED.svg_key,
        custom_specs = EXCLUDED.custom_specs;

    INSERT INTO public.products (
        id, name, sku, description, image, purchase_price, selling_price, wholesale_price,
        vat_rate, discount, unit, stock, min_stock_alert, category, type, status, notes, svg_key, custom_specs
    ) VALUES (
        'prod-win-transom',
        'Transom Window',
        'WIN-TRANSOM',
        'A horizontal window unit mounted directly above an exterior or interior door transom bar, or above a large picture window. Borrows natural daylight and circulates gentle air between rooms. Includes Solid Hardwood frame, Beveled Decorative Glass, multi-point locking hardware, and standard 30" – 72" sizing.',
        NULL,
        176,
        320,
        262,
        20,
        0,
        'unit',
        25,
        5,
        'Windows & Glazing',
        'product',
        'active',
        'U-Factor: 0.24 – 0.28 | SHGC: 0.25 – 0.30 | Energy Star: Certified',
        'transom',
        '{"U-Factor":"0.24 – 0.28","SHGC":"0.25 – 0.30","Sound STC":"32 – 36 dB","Standard Dimensions":"30\" – 72\"","Energy Rating":"Certified","Opening Mechanism":"Fixed or top-hopper operable narrow horizontal window positioned over a door or window"}'::jsonb
    )
    ON CONFLICT (id) DO UPDATE SET
        name = EXCLUDED.name,
        sku = EXCLUDED.sku,
        description = EXCLUDED.description,
        image = EXCLUDED.image,
        purchase_price = EXCLUDED.purchase_price,
        selling_price = EXCLUDED.selling_price,
        wholesale_price = EXCLUDED.wholesale_price,
        vat_rate = EXCLUDED.vat_rate,
        discount = EXCLUDED.discount,
        unit = EXCLUDED.unit,
        stock = EXCLUDED.stock,
        min_stock_alert = EXCLUDED.min_stock_alert,
        category = EXCLUDED.category,
        type = EXCLUDED.type,
        status = EXCLUDED.status,
        notes = EXCLUDED.notes,
        svg_key = EXCLUDED.svg_key,
        custom_specs = EXCLUDED.custom_specs;

    INSERT INTO public.products (
        id, name, sku, description, image, purchase_price, selling_price, wholesale_price,
        vat_rate, discount, unit, stock, min_stock_alert, category, type, status, notes, svg_key, custom_specs
    ) VALUES (
        'prod-win-garden',
        'Garden Window',
        'WIN-GARDEN',
        'Extends outward from the house with glass on the top, front, and sides, plus an interior glass shelf. Acts as a miniature indoor greenhouse for growing fresh herbs, succulents, and flowers year-round. Includes Multi-Chamber Vinyl frame, Tempered Safety Glass Roof, multi-point locking hardware, and standard 36" – 60" sizing.',
        NULL,
        490,
        890,
        730,
        20,
        0,
        'unit',
        25,
        5,
        'Windows & Glazing',
        'product',
        'active',
        'U-Factor: 0.26 – 0.32 | SHGC: 0.28 – 0.35 | Energy Star: Certified',
        'garden',
        '{"U-Factor":"0.26 – 0.32","SHGC":"0.28 – 0.35","Sound STC":"31 – 35 dB","Standard Dimensions":"36\" – 60\"","Energy Rating":"Certified","Opening Mechanism":"Three-dimensional glass box with sloped glass roof and operable side venting casements"}'::jsonb
    )
    ON CONFLICT (id) DO UPDATE SET
        name = EXCLUDED.name,
        sku = EXCLUDED.sku,
        description = EXCLUDED.description,
        image = EXCLUDED.image,
        purchase_price = EXCLUDED.purchase_price,
        selling_price = EXCLUDED.selling_price,
        wholesale_price = EXCLUDED.wholesale_price,
        vat_rate = EXCLUDED.vat_rate,
        discount = EXCLUDED.discount,
        unit = EXCLUDED.unit,
        stock = EXCLUDED.stock,
        min_stock_alert = EXCLUDED.min_stock_alert,
        category = EXCLUDED.category,
        type = EXCLUDED.type,
        status = EXCLUDED.status,
        notes = EXCLUDED.notes,
        svg_key = EXCLUDED.svg_key,
        custom_specs = EXCLUDED.custom_specs;

    INSERT INTO public.products (
        id, name, sku, description, image, purchase_price, selling_price, wholesale_price,
        vat_rate, discount, unit, stock, min_stock_alert, category, type, status, notes, svg_key, custom_specs
    ) VALUES (
        'prod-win-french_casement',
        'French Casement Window',
        'WIN-FRENCH-CASEMENT',
        'Two side-by-side sashes that swing outward from the center without a fixed central vertical mullion (using a flying stile). When fully opened, it creates an uninterrupted wide aperture to the outdoors. Includes Solid Timber Pine / Mahogany frame, Triple Pane Acoustic Low-E Argon, multi-point locking hardware, and standard 36" – 72" sizing.',
        NULL,
        380,
        690,
        566,
        20,
        0,
        'unit',
        25,
        5,
        'Windows & Glazing',
        'product',
        'active',
        'U-Factor: 0.23 – 0.27 | SHGC: 0.25 – 0.31 | Energy Star: Most Efficient',
        'french_casement',
        '{"U-Factor":"0.23 – 0.27","SHGC":"0.25 – 0.31","Sound STC":"33 – 38 dB","Standard Dimensions":"36\" – 72\"","Energy Rating":"Most Efficient","Opening Mechanism":"Dual side-hinged sashes open outwards with no center post or vertical mullion"}'::jsonb
    )
    ON CONFLICT (id) DO UPDATE SET
        name = EXCLUDED.name,
        sku = EXCLUDED.sku,
        description = EXCLUDED.description,
        image = EXCLUDED.image,
        purchase_price = EXCLUDED.purchase_price,
        selling_price = EXCLUDED.selling_price,
        wholesale_price = EXCLUDED.wholesale_price,
        vat_rate = EXCLUDED.vat_rate,
        discount = EXCLUDED.discount,
        unit = EXCLUDED.unit,
        stock = EXCLUDED.stock,
        min_stock_alert = EXCLUDED.min_stock_alert,
        category = EXCLUDED.category,
        type = EXCLUDED.type,
        status = EXCLUDED.status,
        notes = EXCLUDED.notes,
        svg_key = EXCLUDED.svg_key,
        custom_specs = EXCLUDED.custom_specs;

    INSERT INTO public.products (
        id, name, sku, description, image, purchase_price, selling_price, wholesale_price,
        vat_rate, discount, unit, stock, min_stock_alert, category, type, status, notes, svg_key, custom_specs
    ) VALUES (
        'prod-win-dormer',
        'Dormer Window',
        'WIN-DORMER',
        'A vertical window built into a small pitched roof projection extending out from a sloping roof. Transforms cramped dark attics into livable, sunlit bedrooms and creates romantic storybook curb appeal. Includes Clad Wood frame, Double Pane Low-E, multi-point locking hardware, and standard 24" – 42" sizing.',
        NULL,
        297,
        540,
        443,
        20,
        0,
        'unit',
        25,
        5,
        'Windows & Glazing',
        'product',
        'active',
        'U-Factor: 0.24 – 0.29 | SHGC: 0.26 – 0.32 | Energy Star: Certified',
        'dormer',
        '{"U-Factor":"0.24 – 0.29","SHGC":"0.26 – 0.32","Sound STC":"32 – 36 dB","Standard Dimensions":"24\" – 42\"","Energy Rating":"Certified","Opening Mechanism":"Vertical sash unit set in a dedicated structural roof-gable projection"}'::jsonb
    )
    ON CONFLICT (id) DO UPDATE SET
        name = EXCLUDED.name,
        sku = EXCLUDED.sku,
        description = EXCLUDED.description,
        image = EXCLUDED.image,
        purchase_price = EXCLUDED.purchase_price,
        selling_price = EXCLUDED.selling_price,
        wholesale_price = EXCLUDED.wholesale_price,
        vat_rate = EXCLUDED.vat_rate,
        discount = EXCLUDED.discount,
        unit = EXCLUDED.unit,
        stock = EXCLUDED.stock,
        min_stock_alert = EXCLUDED.min_stock_alert,
        category = EXCLUDED.category,
        type = EXCLUDED.type,
        status = EXCLUDED.status,
        notes = EXCLUDED.notes,
        svg_key = EXCLUDED.svg_key,
        custom_specs = EXCLUDED.custom_specs;

    INSERT INTO public.products (
        id, name, sku, description, image, purchase_price, selling_price, wholesale_price,
        vat_rate, discount, unit, stock, min_stock_alert, category, type, status, notes, svg_key, custom_specs
    ) VALUES (
        'prod-win-clerestory',
        'Clerestory Window',
        'WIN-CLERESTORY',
        'A horizontal band of windows installed high along an interior or exterior wall near the roofline. Brings abundant natural light deep into the building core while maintaining 100% privacy and freeing up wall space for furniture. Includes Thermal Break Architectural Aluminum frame, Solar Heat Reflective Low-E Glass, multi-point locking hardware, and standard 48" – 144" sizing.',
        NULL,
        286,
        520,
        426,
        20,
        0,
        'unit',
        25,
        5,
        'Windows & Glazing',
        'product',
        'active',
        'U-Factor: 0.22 – 0.27 | SHGC: 0.22 – 0.28 | Energy Star: Most Efficient',
        'clerestory',
        '{"U-Factor":"0.22 – 0.27","SHGC":"0.22 – 0.28","Sound STC":"34 – 38 dB","Standard Dimensions":"48\" – 144\"","Energy Rating":"Most Efficient","Opening Mechanism":"Fixed or power-vented horizontal ribbon windows placed high near ceiling rooflines"}'::jsonb
    )
    ON CONFLICT (id) DO UPDATE SET
        name = EXCLUDED.name,
        sku = EXCLUDED.sku,
        description = EXCLUDED.description,
        image = EXCLUDED.image,
        purchase_price = EXCLUDED.purchase_price,
        selling_price = EXCLUDED.selling_price,
        wholesale_price = EXCLUDED.wholesale_price,
        vat_rate = EXCLUDED.vat_rate,
        discount = EXCLUDED.discount,
        unit = EXCLUDED.unit,
        stock = EXCLUDED.stock,
        min_stock_alert = EXCLUDED.min_stock_alert,
        category = EXCLUDED.category,
        type = EXCLUDED.type,
        status = EXCLUDED.status,
        notes = EXCLUDED.notes,
        svg_key = EXCLUDED.svg_key,
        custom_specs = EXCLUDED.custom_specs;

    INSERT INTO public.products (
        id, name, sku, description, image, purchase_price, selling_price, wholesale_price,
        vat_rate, discount, unit, stock, min_stock_alert, category, type, status, notes, svg_key, custom_specs
    ) VALUES (
        'prod-win-round_oculus',
        'Round Window',
        'WIN-ROUND-OCULUS',
        'A full 360° circular architectural window (also known as an Oculus or Bullseye window). Adds nautical flair, historical symmetry, and focal point geometry to gable peaks, stairwells, and powder rooms. Includes Molded Polyurethane Core with Wood Interior frame, Beveled Decorative Low-E Glass, multi-point locking hardware, and standard 24" – 48" Dia sizing.',
        NULL,
        270,
        490,
        402,
        20,
        0,
        'unit',
        25,
        5,
        'Windows & Glazing',
        'product',
        'active',
        'U-Factor: 0.25 – 0.30 | SHGC: 0.26 – 0.32 | Energy Star: Certified',
        'round_oculus',
        '{"U-Factor":"0.25 – 0.30","SHGC":"0.26 – 0.32","Sound STC":"31 – 35 dB","Standard Dimensions":"24\" – 48\" Dia","Energy Rating":"Certified","Opening Mechanism":"Fixed circular geometric frame with 4-way cross or starburst muntin grids"}'::jsonb
    )
    ON CONFLICT (id) DO UPDATE SET
        name = EXCLUDED.name,
        sku = EXCLUDED.sku,
        description = EXCLUDED.description,
        image = EXCLUDED.image,
        purchase_price = EXCLUDED.purchase_price,
        selling_price = EXCLUDED.selling_price,
        wholesale_price = EXCLUDED.wholesale_price,
        vat_rate = EXCLUDED.vat_rate,
        discount = EXCLUDED.discount,
        unit = EXCLUDED.unit,
        stock = EXCLUDED.stock,
        min_stock_alert = EXCLUDED.min_stock_alert,
        category = EXCLUDED.category,
        type = EXCLUDED.type,
        status = EXCLUDED.status,
        notes = EXCLUDED.notes,
        svg_key = EXCLUDED.svg_key,
        custom_specs = EXCLUDED.custom_specs;

    INSERT INTO public.products (
        id, name, sku, description, image, purchase_price, selling_price, wholesale_price,
        vat_rate, discount, unit, stock, min_stock_alert, category, type, status, notes, svg_key, custom_specs
    ) VALUES (
        'prod-win-octagon',
        'Geometric Window',
        'WIN-OCTAGON',
        'An eight-sided geometric polygon window designed to create visual rhythm, classical symmetry, and striking light diffusion in entryways, foyers, master bathrooms, and attic gables. Includes Cellular PVC frame, Leaded Diamond Low-E, multi-point locking hardware, and standard 20" – 42" Dia sizing.',
        NULL,
        286,
        520,
        426,
        20,
        0,
        'unit',
        25,
        5,
        'Windows & Glazing',
        'product',
        'active',
        'U-Factor: 0.24 – 0.29 | SHGC: 0.25 – 0.31 | Energy Star: Certified',
        'octagon',
        '{"U-Factor":"0.24 – 0.29","SHGC":"0.25 – 0.31","Sound STC":"30 – 35 dB","Standard Dimensions":"20\" – 42\" Dia","Energy Rating":"Certified","Opening Mechanism":"Fixed eight-sided polygon with optional central diamond or spoke leaded grids"}'::jsonb
    )
    ON CONFLICT (id) DO UPDATE SET
        name = EXCLUDED.name,
        sku = EXCLUDED.sku,
        description = EXCLUDED.description,
        image = EXCLUDED.image,
        purchase_price = EXCLUDED.purchase_price,
        selling_price = EXCLUDED.selling_price,
        wholesale_price = EXCLUDED.wholesale_price,
        vat_rate = EXCLUDED.vat_rate,
        discount = EXCLUDED.discount,
        unit = EXCLUDED.unit,
        stock = EXCLUDED.stock,
        min_stock_alert = EXCLUDED.min_stock_alert,
        category = EXCLUDED.category,
        type = EXCLUDED.type,
        status = EXCLUDED.status,
        notes = EXCLUDED.notes,
        svg_key = EXCLUDED.svg_key,
        custom_specs = EXCLUDED.custom_specs;

    INSERT INTO public.products (
        id, name, sku, description, image, purchase_price, selling_price, wholesale_price,
        vat_rate, discount, unit, stock, min_stock_alert, category, type, status, notes, svg_key, custom_specs
    ) VALUES (
        'prod-win-trapezoid',
        'Trapezoid Window',
        'WIN-TRAPEZOID',
        'A customized raked geometric polygon engineered to follow the precise slope of cathedral ceilings and vaulted rooflines, creating panoramic cathedral glass walls and maximizing celestial views. Includes Thermal Break Aluminum frame, Solar Heat Ban Low-E 366, multi-point locking hardware, and standard 24" – 72" sizing.',
        NULL,
        374,
        680,
        558,
        20,
        0,
        'unit',
        25,
        5,
        'Windows & Glazing',
        'product',
        'active',
        'U-Factor: 0.22 – 0.27 | SHGC: 0.23 – 0.28 | Energy Star: Most Efficient',
        'trapezoid',
        '{"U-Factor":"0.22 – 0.27","SHGC":"0.23 – 0.28","Sound STC":"32 – 36 dB","Standard Dimensions":"24\" – 72\"","Energy Rating":"Most Efficient","Opening Mechanism":"Fixed geometric sloped raked top frame aligned to vaulted roof pitches"}'::jsonb
    )
    ON CONFLICT (id) DO UPDATE SET
        name = EXCLUDED.name,
        sku = EXCLUDED.sku,
        description = EXCLUDED.description,
        image = EXCLUDED.image,
        purchase_price = EXCLUDED.purchase_price,
        selling_price = EXCLUDED.selling_price,
        wholesale_price = EXCLUDED.wholesale_price,
        vat_rate = EXCLUDED.vat_rate,
        discount = EXCLUDED.discount,
        unit = EXCLUDED.unit,
        stock = EXCLUDED.stock,
        min_stock_alert = EXCLUDED.min_stock_alert,
        category = EXCLUDED.category,
        type = EXCLUDED.type,
        status = EXCLUDED.status,
        notes = EXCLUDED.notes,
        svg_key = EXCLUDED.svg_key,
        custom_specs = EXCLUDED.custom_specs;

    INSERT INTO public.products (
        id, name, sku, description, image, purchase_price, selling_price, wholesale_price,
        vat_rate, discount, unit, stock, min_stock_alert, category, type, status, notes, svg_key, custom_specs
    ) VALUES (
        'prod-win-triangle',
        'Triangle Window',
        'WIN-TRIANGLE',
        'Engineered specifically for the topmost apex of roof gables. Triangle windows capture rising daylight and illuminate ceiling timber beams without compromising structural rafter tie-ins. Includes Structural Thermal Aluminum frame, Solar Controlled Double Glaze, multi-point locking hardware, and standard 36" – 84" sizing.',
        NULL,
        336,
        610,
        500,
        20,
        0,
        'unit',
        25,
        5,
        'Windows & Glazing',
        'product',
        'active',
        'U-Factor: 0.23 – 0.28 | SHGC: 0.24 – 0.30 | Energy Star: Most Efficient',
        'triangle',
        '{"U-Factor":"0.23 – 0.28","SHGC":"0.24 – 0.30","Sound STC":"31 – 35 dB","Standard Dimensions":"36\" – 84\"","Energy Rating":"Most Efficient","Opening Mechanism":"Fixed triangular apex frame (Isosceles, Right, or Equilateral geometry)"}'::jsonb
    )
    ON CONFLICT (id) DO UPDATE SET
        name = EXCLUDED.name,
        sku = EXCLUDED.sku,
        description = EXCLUDED.description,
        image = EXCLUDED.image,
        purchase_price = EXCLUDED.purchase_price,
        selling_price = EXCLUDED.selling_price,
        wholesale_price = EXCLUDED.wholesale_price,
        vat_rate = EXCLUDED.vat_rate,
        discount = EXCLUDED.discount,
        unit = EXCLUDED.unit,
        stock = EXCLUDED.stock,
        min_stock_alert = EXCLUDED.min_stock_alert,
        category = EXCLUDED.category,
        type = EXCLUDED.type,
        status = EXCLUDED.status,
        notes = EXCLUDED.notes,
        svg_key = EXCLUDED.svg_key,
        custom_specs = EXCLUDED.custom_specs;

    INSERT INTO public.products (
        id, name, sku, description, image, purchase_price, selling_price, wholesale_price,
        vat_rate, discount, unit, stock, min_stock_alert, category, type, status, notes, svg_key, custom_specs
    ) VALUES (
        'prod-win-gothic_lancet',
        'Gothic Arch Window',
        'WIN-GOTHIC-LANCET',
        'Distinguished by a sharp pointed arch apex and medieval filigree tracery. Infuses historic grandeur, ecclesiastical elegance, and dramatic vertical perspective into churches, library towers, and revival mansions. Includes Solid Mahogany / Oak frame, Leaded Antique Restoration Glass, multi-point locking hardware, and standard 24" – 48" sizing.',
        NULL,
        523,
        950,
        779,
        20,
        0,
        'unit',
        25,
        5,
        'Windows & Glazing',
        'product',
        'active',
        'U-Factor: 0.25 – 0.30 | SHGC: 0.26 – 0.32 | Energy Star: Certified',
        'gothic_lancet',
        '{"U-Factor":"0.25 – 0.30","SHGC":"0.26 – 0.32","Sound STC":"30 – 34 dB","Standard Dimensions":"24\" – 48\"","Energy Rating":"Certified","Opening Mechanism":"Fixed or operable pointed Gothic lancet arch with trefoil and tracery fretwork"}'::jsonb
    )
    ON CONFLICT (id) DO UPDATE SET
        name = EXCLUDED.name,
        sku = EXCLUDED.sku,
        description = EXCLUDED.description,
        image = EXCLUDED.image,
        purchase_price = EXCLUDED.purchase_price,
        selling_price = EXCLUDED.selling_price,
        wholesale_price = EXCLUDED.wholesale_price,
        vat_rate = EXCLUDED.vat_rate,
        discount = EXCLUDED.discount,
        unit = EXCLUDED.unit,
        stock = EXCLUDED.stock,
        min_stock_alert = EXCLUDED.min_stock_alert,
        category = EXCLUDED.category,
        type = EXCLUDED.type,
        status = EXCLUDED.status,
        notes = EXCLUDED.notes,
        svg_key = EXCLUDED.svg_key,
        custom_specs = EXCLUDED.custom_specs;

    INSERT INTO public.products (
        id, name, sku, description, image, purchase_price, selling_price, wholesale_price,
        vat_rate, discount, unit, stock, min_stock_alert, category, type, status, notes, svg_key, custom_specs
    ) VALUES (
        'prod-win-bifold',
        'Bi-Fold Window',
        'WIN-BIFOLD',
        'A multi-leaf folding accordion window system that opens seamlessly to reveal a 100% unobstructed panoramic pass-through, effortlessly bridging indoor kitchens with outdoor dining decks. Includes Commercial-Grade Thermal Aluminum frame, Tempered Double Low-E Argon, multi-point locking hardware, and standard 60" – 180" sizing.',
        NULL,
        798,
        1450,
        1189,
        20,
        0,
        'unit',
        25,
        5,
        'Windows & Glazing',
        'product',
        'active',
        'U-Factor: 0.24 – 0.28 | SHGC: 0.22 – 0.27 | Energy Star: Most Efficient',
        'bifold',
        '{"U-Factor":"0.24 – 0.28","SHGC":"0.22 – 0.27","Sound STC":"33 – 38 dB","Standard Dimensions":"60\" – 180\"","Energy Rating":"Most Efficient","Opening Mechanism":"Multi-panel top-hung accordion sashes that fold flat against side jambs"}'::jsonb
    )
    ON CONFLICT (id) DO UPDATE SET
        name = EXCLUDED.name,
        sku = EXCLUDED.sku,
        description = EXCLUDED.description,
        image = EXCLUDED.image,
        purchase_price = EXCLUDED.purchase_price,
        selling_price = EXCLUDED.selling_price,
        wholesale_price = EXCLUDED.wholesale_price,
        vat_rate = EXCLUDED.vat_rate,
        discount = EXCLUDED.discount,
        unit = EXCLUDED.unit,
        stock = EXCLUDED.stock,
        min_stock_alert = EXCLUDED.min_stock_alert,
        category = EXCLUDED.category,
        type = EXCLUDED.type,
        status = EXCLUDED.status,
        notes = EXCLUDED.notes,
        svg_key = EXCLUDED.svg_key,
        custom_specs = EXCLUDED.custom_specs;

    INSERT INTO public.products (
        id, name, sku, description, image, purchase_price, selling_price, wholesale_price,
        vat_rate, discount, unit, stock, min_stock_alert, category, type, status, notes, svg_key, custom_specs
    ) VALUES (
        'prod-win-pivot',
        'Pivot Window',
        'WIN-PIVOT',
        'Swivels around a central axis allowing extraordinary single-pane oversized glass surfaces. When swung open, warm air escapes above the pivot point while cool fresh air draws in below. Includes Heavy Gauge Architectural Aluminum frame, Triple Pane Low-E with Argon, multi-point locking hardware, and standard 36" – 72" sizing.',
        NULL,
        616,
        1120,
        918,
        20,
        0,
        'unit',
        25,
        5,
        'Windows & Glazing',
        'product',
        'active',
        'U-Factor: 0.22 – 0.26 | SHGC: 0.24 – 0.29 | Energy Star: Most Efficient',
        'pivot',
        '{"U-Factor":"0.22 – 0.26","SHGC":"0.24 – 0.29","Sound STC":"34 – 38 dB","Standard Dimensions":"36\" – 72\"","Energy Rating":"Most Efficient","Opening Mechanism":"Rotates smoothly 360° on central top/bottom or horizontal mid-point heavy-duty pivot axles"}'::jsonb
    )
    ON CONFLICT (id) DO UPDATE SET
        name = EXCLUDED.name,
        sku = EXCLUDED.sku,
        description = EXCLUDED.description,
        image = EXCLUDED.image,
        purchase_price = EXCLUDED.purchase_price,
        selling_price = EXCLUDED.selling_price,
        wholesale_price = EXCLUDED.wholesale_price,
        vat_rate = EXCLUDED.vat_rate,
        discount = EXCLUDED.discount,
        unit = EXCLUDED.unit,
        stock = EXCLUDED.stock,
        min_stock_alert = EXCLUDED.min_stock_alert,
        category = EXCLUDED.category,
        type = EXCLUDED.type,
        status = EXCLUDED.status,
        notes = EXCLUDED.notes,
        svg_key = EXCLUDED.svg_key,
        custom_specs = EXCLUDED.custom_specs;

    INSERT INTO public.products (
        id, name, sku, description, image, purchase_price, selling_price, wholesale_price,
        vat_rate, discount, unit, stock, min_stock_alert, category, type, status, notes, svg_key, custom_specs
    ) VALUES (
        'prod-win-corner_butt',
        'Corner Glass Window',
        'WIN-CORNER-BUTT',
        'Engineered with two monolithic glass panes meeting at a seamless 90° angle sealed with structural transparent silicone. Eliminates heavy corner posts for completely uninterrupted panoramic horizon views. Includes Structural Concealed Sub-Frame Aluminum frame, 10mm Tempered + 10mm Laminated Low-E Glass, multi-point locking hardware, and standard 36" × 36" to 96" × 96" sizing.',
        NULL,
        908,
        1650,
        1353,
        20,
        0,
        'unit',
        25,
        5,
        'Windows & Glazing',
        'product',
        'active',
        'U-Factor: 0.24 – 0.28 | SHGC: 0.23 – 0.28 | Energy Star: Most Efficient',
        'corner_butt',
        '{"U-Factor":"0.24 – 0.28","SHGC":"0.23 – 0.28","Sound STC":"33 – 37 dB","Standard Dimensions":"36\" × 36\" to 96\" × 96\"","Energy Rating":"Most Efficient","Opening Mechanism":"Fixed 90° dual glass panes joined by structural crystal-clear silicone (Zero Corner Post)"}'::jsonb
    )
    ON CONFLICT (id) DO UPDATE SET
        name = EXCLUDED.name,
        sku = EXCLUDED.sku,
        description = EXCLUDED.description,
        image = EXCLUDED.image,
        purchase_price = EXCLUDED.purchase_price,
        selling_price = EXCLUDED.selling_price,
        wholesale_price = EXCLUDED.wholesale_price,
        vat_rate = EXCLUDED.vat_rate,
        discount = EXCLUDED.discount,
        unit = EXCLUDED.unit,
        stock = EXCLUDED.stock,
        min_stock_alert = EXCLUDED.min_stock_alert,
        category = EXCLUDED.category,
        type = EXCLUDED.type,
        status = EXCLUDED.status,
        notes = EXCLUDED.notes,
        svg_key = EXCLUDED.svg_key,
        custom_specs = EXCLUDED.custom_specs;

    INSERT INTO public.products (
        id, name, sku, description, image, purchase_price, selling_price, wholesale_price,
        vat_rate, discount, unit, stock, min_stock_alert, category, type, status, notes, svg_key, custom_specs
    ) VALUES (
        'prod-win-pass_through',
        'Pass-Through Window',
        'WIN-PASS-THROUGH',
        'The ultimate kitchen bar window. Driven by automotive-grade gas struts, the entire sash effortlessly glides upward and stays open horizontally, converting your kitchen countertop into an outdoor entertaining servery. Includes Thermally Broken Commercial Aluminum frame, Double Pane Low-E Tempered Safety Glass, multi-point locking hardware, and standard 48" – 108" sizing.',
        NULL,
        704,
        1280,
        1050,
        20,
        0,
        'unit',
        25,
        5,
        'Windows & Glazing',
        'product',
        'active',
        'U-Factor: 0.23 – 0.27 | SHGC: 0.24 – 0.29 | Energy Star: Most Efficient',
        'pass_through',
        '{"U-Factor":"0.23 – 0.27","SHGC":"0.24 – 0.29","Sound STC":"32 – 36 dB","Standard Dimensions":"48\" – 108\"","Energy Rating":"Most Efficient","Opening Mechanism":"Single large top-hinged sash swings upward 80° supported by dual gas-assist compression struts"}'::jsonb
    )
    ON CONFLICT (id) DO UPDATE SET
        name = EXCLUDED.name,
        sku = EXCLUDED.sku,
        description = EXCLUDED.description,
        image = EXCLUDED.image,
        purchase_price = EXCLUDED.purchase_price,
        selling_price = EXCLUDED.selling_price,
        wholesale_price = EXCLUDED.wholesale_price,
        vat_rate = EXCLUDED.vat_rate,
        discount = EXCLUDED.discount,
        unit = EXCLUDED.unit,
        stock = EXCLUDED.stock,
        min_stock_alert = EXCLUDED.min_stock_alert,
        category = EXCLUDED.category,
        type = EXCLUDED.type,
        status = EXCLUDED.status,
        notes = EXCLUDED.notes,
        svg_key = EXCLUDED.svg_key,
        custom_specs = EXCLUDED.custom_specs;

    INSERT INTO public.products (
        id, name, sku, description, image, purchase_price, selling_price, wholesale_price,
        vat_rate, discount, unit, stock, min_stock_alert, category, type, status, notes, svg_key, custom_specs
    ) VALUES (
        'prod-win-eyebrow',
        'Eyebrow Window',
        'WIN-EYEBROW',
        'A gentle, low-rise arch curve (resembling a human eyebrow) that crowns square windows or dormers. Adds refined softness and European country romance without the extreme height needed for full semicircles. Includes Solid Curved Wood (Pine, Fir, Mahogany) frame, Low-E Argon Double Glaze with Radial Muntins, multi-point locking hardware, and standard 36" – 72" sizing.',
        NULL,
        407,
        740,
        607,
        20,
        0,
        'unit',
        25,
        5,
        'Windows & Glazing',
        'product',
        'active',
        'U-Factor: 0.24 – 0.29 | SHGC: 0.25 – 0.31 | Energy Star: Certified',
        'eyebrow',
        '{"U-Factor":"0.24 – 0.29","SHGC":"0.25 – 0.31","Sound STC":"31 – 35 dB","Standard Dimensions":"36\" – 72\"","Energy Rating":"Certified","Opening Mechanism":"Fixed or bottom-operable window with shallow elliptical curved segmental top header"}'::jsonb
    )
    ON CONFLICT (id) DO UPDATE SET
        name = EXCLUDED.name,
        sku = EXCLUDED.sku,
        description = EXCLUDED.description,
        image = EXCLUDED.image,
        purchase_price = EXCLUDED.purchase_price,
        selling_price = EXCLUDED.selling_price,
        wholesale_price = EXCLUDED.wholesale_price,
        vat_rate = EXCLUDED.vat_rate,
        discount = EXCLUDED.discount,
        unit = EXCLUDED.unit,
        stock = EXCLUDED.stock,
        min_stock_alert = EXCLUDED.min_stock_alert,
        category = EXCLUDED.category,
        type = EXCLUDED.type,
        status = EXCLUDED.status,
        notes = EXCLUDED.notes,
        svg_key = EXCLUDED.svg_key,
        custom_specs = EXCLUDED.custom_specs;

    INSERT INTO public.products (
        id, name, sku, description, image, purchase_price, selling_price, wholesale_price,
        vat_rate, discount, unit, stock, min_stock_alert, category, type, status, notes, svg_key, custom_specs
    ) VALUES (
        'prod-win-quarter_round',
        'Quarter-Round Window',
        'WIN-QUARTER-ROUND',
        'A 90-degree quadrant window often installed in pairs framing a central picture window, or individually in roof corners and upper wall shoulders. Produces a radiant sunburst light pattern. Includes Curved uPVC / Vinyl frame, Sunburst Grille Double Glaze, multi-point locking hardware, and standard 18" – 36" sizing.',
        NULL,
        215,
        390,
        320,
        20,
        0,
        'unit',
        25,
        5,
        'Windows & Glazing',
        'product',
        'active',
        'U-Factor: 0.25 – 0.30 | SHGC: 0.26 – 0.32 | Energy Star: Certified',
        'quarter_round',
        '{"U-Factor":"0.25 – 0.30","SHGC":"0.26 – 0.32","Sound STC":"30 – 34 dB","Standard Dimensions":"18\" – 36\"","Energy Rating":"Certified","Opening Mechanism":"Fixed 90° quadrant corner radius frame with decorative radial sunburst muntin spokes"}'::jsonb
    )
    ON CONFLICT (id) DO UPDATE SET
        name = EXCLUDED.name,
        sku = EXCLUDED.sku,
        description = EXCLUDED.description,
        image = EXCLUDED.image,
        purchase_price = EXCLUDED.purchase_price,
        selling_price = EXCLUDED.selling_price,
        wholesale_price = EXCLUDED.wholesale_price,
        vat_rate = EXCLUDED.vat_rate,
        discount = EXCLUDED.discount,
        unit = EXCLUDED.unit,
        stock = EXCLUDED.stock,
        min_stock_alert = EXCLUDED.min_stock_alert,
        category = EXCLUDED.category,
        type = EXCLUDED.type,
        status = EXCLUDED.status,
        notes = EXCLUDED.notes,
        svg_key = EXCLUDED.svg_key,
        custom_specs = EXCLUDED.custom_specs;

    INSERT INTO public.products (
        id, name, sku, description, image, purchase_price, selling_price, wholesale_price,
        vat_rate, discount, unit, stock, min_stock_alert, category, type, status, notes, svg_key, custom_specs
    ) VALUES (
        'prod-win-stained_glass',
        'Stained Glass Window',
        'WIN-STAINED-GLASS',
        'An artisan architectural masterpiece. Handcrafted from colorful art glass tiles, faceted jewels, and hand-soldered lead/zinc cames, protected between dual clear thermal Low-E safety glass panes for modern insulation. Includes Solid Hardwood (Mahogany / Walnut / Oak) frame, Triple-Glazed Encapsulated Leaded Art Glass, multi-point locking hardware, and standard 20" – 48" sizing.',
        NULL,
        649,
        1180,
        968,
        20,
        0,
        'unit',
        25,
        5,
        'Windows & Glazing',
        'product',
        'active',
        'U-Factor: 0.23 – 0.28 | SHGC: 0.22 – 0.26 | Energy Star: Most Efficient',
        'stained_glass',
        '{"U-Factor":"0.23 – 0.28","SHGC":"0.22 – 0.26","Sound STC":"34 – 38 dB","Standard Dimensions":"20\" – 48\"","Energy Rating":"Most Efficient","Opening Mechanism":"Fixed artisan leaded zinc came panel with hand-cut colored cathedral and beveled glass"}'::jsonb
    )
    ON CONFLICT (id) DO UPDATE SET
        name = EXCLUDED.name,
        sku = EXCLUDED.sku,
        description = EXCLUDED.description,
        image = EXCLUDED.image,
        purchase_price = EXCLUDED.purchase_price,
        selling_price = EXCLUDED.selling_price,
        wholesale_price = EXCLUDED.wholesale_price,
        vat_rate = EXCLUDED.vat_rate,
        discount = EXCLUDED.discount,
        unit = EXCLUDED.unit,
        stock = EXCLUDED.stock,
        min_stock_alert = EXCLUDED.min_stock_alert,
        category = EXCLUDED.category,
        type = EXCLUDED.type,
        status = EXCLUDED.status,
        notes = EXCLUDED.notes,
        svg_key = EXCLUDED.svg_key,
        custom_specs = EXCLUDED.custom_specs;

END $$;
